services:
  # Aplicação Java
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/alumindDB
      - SPRING_DATASOURCE_USERNAME=alumindUser
      - SPRING_DATASOURCE_PASSWORD=alumindSecret

  # Banco de dados
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=alumindDB'
      - 'POSTGRES_PASSWORD=alumindSecret'
      - 'POSTGRES_USER=alumindUser'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: